name       : python-pyls-spyder
version    : 0.1.1
release    : 1
source     :
    - https://github.com/spyder-ide/pyls-spyder/archive/v0.1.1.tar.gz : 177739da09f829d97ed413171d2c57f6eb679a3f45fe04ac13777ca6b610e8df
homepage   : https://github.com/spyder-ide/pyls-spyder
license    : MIT
component  : programming.python
summary    : Spyder extensions for the python language server (pyls)
description: |
    Spyder extensions for the python-language-server (pyls). This package provides Spyder-specific extras for the Language Server Protocol (LSP) on Python, such as document symbol searching and others.   
builddeps  :
    - python-language-server
    - python-mock
    - python-pytest
rundeps    :
    - python-language-server
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
